### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by supmyhava** [boz3r/Fatebot#2]
I like messing with your bot (:

(03:57:12) <@ME> ?scan -r MY.PAYLOAD
(03:57:12) <@[BOT][F][9758249]> START SCANNING.
(03:58:03) <@[BOT][F][9758249]> Try to login: 125.135.102.241:22
(03:58:04) <@[BOT][F][9758249]> Login success: 125.135.102.241:22
(03:58:05) <@[BOT][F][9758249]> Installing bot: 125.135.102.241:22
(03:59:06) <@[BOT][F][9758249]> Try to login: 82.102.234.7:22
(04:00:55) <@ME> ?stopscan
(04:02:42) <@ME> ?stopscan

He just got stuck

**Comment by supmyhava** [comment]
(04:03:06) * @[BOT][F][9758249] (~BOTF9@B9F95C80.810C1C04.E2024C58.IP) Quit (Connection closed)
(04:03:25) • (Join) • [BOT][R][2781027] (~BOTR2@B9F95C80.810C1C04.E2024C58.IP) Has Joined #ME (Users: 3)
(04:03:37) * ME sets mode: +o [BOT][R][2781027]
(04:03:43) <@ME> ?scan -kr MY.PAYLOAD
(04:03:44) <@[BOT][R][2781027]> START SCANNING.
(04:09:00) <@ME> ?stopscan

again =\

**Comment by supmyhava** [comment]
(04:13:33) <@ME> ?scan -usa MY.PAYLOAD
(04:13:34) <@[BOT][I][4321226]> START SCANNING.
(04:13:38) <@[BOT][I][4321226]> Try to login: 18.188.90.138:22
(04:13:46) <@[BOT][I][4321226]> Try to login: 18.222.39.67:22
(04:14:02) <@[BOT][I][4321226]> Try to login: 104.248.99.173:22
(04:14:05) <@[BOT][I][4321226]> Try to login: 35.194.105.75:22
(04:14:15) <@[BOT][I][4321226]> Try to login: 34.72.50.155:22
(04:14:17) <@[BOT][I][4321226]> Try to login: 165.227.233.233:22
(04:14:27) <@[BOT][I][4321226]> Try to login: 34.133.248.207:22
(04:14:27) <@[BOT][I][4321226]> Try to login: 34.136.61.221:22
(04:14:31) <@[BOT][I][4321226]> STOP SCANNING.
another thing XD

**Comment by boz3r** [comment]
I will fix it in a new version i'm really sorry about that. it will release soon (Maybe today).
But some time it will be a network problem of **bot device** like slow internet connection for example.

**Comment by boz3r** [comment]
I have release v0.6.1 now. Thanks you a lot for report the bug.

**Comment by supmyhava** [comment]
> I will fix it in a new version i'm really sorry about that. it will release soon (Maybe today). But some time it will be a network problem of **bot device** like slow internet connection for example.

nah the network of my server is great 2GB download
and 2GB upload (:



> I have release **v0.6.1** now. Thanks you a lot for report the bug.

nicee i will try that in a few hours

**Comment by supmyhava** [comment]
> Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> 
> oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.

great update
also liked the new icons you put in the scan section (:

**Comment by supmyhava** [comment]
Another offer for you is to cancel those messages on Failed login
because the bot is keep getting Excess Flood also when i created my own irc server and i set the maximum overflow messages possible
 exceeds class::recvq (32805 > 32768) (Client sending too much data)

**Comment by boz3r** [comment]
> Another offer for you is to cancel those messages on Failed login because the bot is keep getting Excess Flood also when i created my own irc server and i set the maximum overflow messages possible exceeds class::recvq (32805 > 32768) (Client sending too much data)

oh ok i'll cut it in a new version.

**Comment by boz3r** [comment]
> > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> 
> great update also liked the new icons you put in the scan section (:

Thank you very much 😆

**Comment by supmyhava** [comment]
> > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > 
> > 
> > great update also liked the new icons you put in the scan section (:
> 
> Thank you very much 😆

hi mate
after a long time i didnt was here
try your bot again

(02:52:46) <@ME> ?scan -cn PAYLOAD.COM/PAY
(02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING...
(02:54:16) * @[ME][U][196] (~MU19@14C849C7.8992B6D3.5C536F8B.IP) Quit (Connection closed)

**Comment by boz3r** [comment]
> > > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > > 
> > > 
> > > great update also liked the new icons you put in the scan section (:
> > 
> > 
> > Thank you very much 😆
> 
> hi mate after a long time i didnt was here try your bot again
> 
> (02:52:46) <@me> ?scan -cn PAYLOAD.COM/PAY (02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING... (02:54:16) * @[ME][U][196] (~[MU19@14C849C7.8992B6D3.5C536F8B.IP](mailto:MU19@14C849C7.8992B6D3.5C536F8B.IP)) Quit (Connection closed)

Is it happened with every bot you scan or just this one? i need to scope the problem for fix that.

**Comment by boz3r** [comment]
> > > > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > > > 
> > > > 
> > > > great update also liked the new icons you put in the scan section (:
> > > 
> > > 
> > > Thank you very much 😆
> > 
> > 
> > hi mate after a long time i didnt was here try your bot again
> > (02:52:46) <@me> ?scan -cn PAYLOAD.COM/PAY (02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING... (02:54:16) * @[ME][U][196] (~[MU19@14C849C7.8992B6D3.5C536F8B.IP](mailto:MU19@14C849C7.8992B6D3.5C536F8B.IP)) Quit (Connection closed)
> 
> Is it happened with every bot you scan or just this one? i need to scope the problem for fix that.

Oh and this one that's you just report to me you scan with you self or not? i really really need to scope a problem for fix that.

**Comment by supmyhava** [comment]
> > > > > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > > > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > > > > 
> > > > > 
> > > > > great update also liked the new icons you put in the scan section (:
> > > > 
> > > > 
> > > > Thank you very much 😆
> > > 
> > > 
> > > hi mate after a long time i didnt was here try your bot again
> > > (02:52:46) <@me> ?scan -cn PAYLOAD.COM/PAY (02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING... (02:54:16) * @[ME][U][196] (~[MU19@14C849C7.8992B6D3.5C536F8B.IP](mailto:MU19@14C849C7.8992B6D3.5C536F8B.IP)) Quit (Connection closed)
> > 
> > 
> > Is it happened with every bot you scan or just this one? i need to scope the problem for fix that.
> 
> Oh and this one that's you just report to me you scan with you self or not? i really really need to scope a problem for fix that.

maybe this will tell you something

panic: runtime error: index out of range [3] with length 2

goroutine 80 [running]:
bot/internal.Recv(0xc00032e3d8, 0x16, 0x3, 0x0, 0xc0001fd6d8)
        /home/me/Fatebot/internal/irc.go:26 +0xd6
bot/internal.ComdSetup(0x3, 0x7d84ec, 0x1, 0xc000219400, 0x1e)
        /home/me/Fatebot/internal/header.go:208 +0x47
bot/internal.SetupCaller(0x7d8b5b, 0x3, 0xc0002344b0)
        /home/me/Fatebot/internal/header.go:212 +0x54
bot/internal.(*Bot).runScan(0xc0000f84b0, 0xa69260, 0x20, 0x20, 0x0, 0xc0001fdf88, 0x4, 0xc00020df88)
        /home/me/Fatebot/internal/scanner.go:271 +0x7d
bot/internal.(*Bot).Scanner.func1(0xc0000f84b0, 0xc0000f8d20, 0xc00002e7e0, 0x1)
        /home/me/Fatebot/internal/scanner.go:330 +0x125
created by bot/internal.(*Bot).Scanner

**Comment by boz3r** [comment]
> > > > > > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > > > > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > > > > > 
> > > > > > 
> > > > > > great update also liked the new icons you put in the scan section (:
> > > > > 
> > > > > 
> > > > > Thank you very much 😆
> > > > 
> > > > 
> > > > hi mate after a long time i didnt was here try your bot again
> > > > (02:52:46) <@me> ?scan -cn PAYLOAD.COM/PAY (02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING... (02:54:16) * @[ME][U][196] (~[MU19@14C849C7.8992B6D3.5C536F8B.IP](mailto:MU19@14C849C7.8992B6D3.5C536F8B.IP)) Quit (Connection closed)
> > > 
> > > 
> > > Is it happened with every bot you scan or just this one? i need to scope the problem for fix that.
> > 
> > 
> > Oh and this one that's you just report to me you scan with you self or not? i really really need to scope a problem for fix that.
> 
> maybe this will tell you something
> 
> panic: runtime error: index out of range [3] with length 2
> 
> goroutine 80 [running]: bot/internal.Recv(0xc00032e3d8, 0x16, 0x3, 0x0, 0xc0001fd6d8) /home/me/Fatebot/internal/irc.go:26 +0xd6 bot/internal.ComdSetup(0x3, 0x7d84ec, 0x1, 0xc000219400, 0x1e) /home/me/Fatebot/internal/header.go:208 +0x47 bot/internal.SetupCaller(0x7d8b5b, 0x3, 0xc0002344b0) /home/me/Fatebot/internal/header.go:212 +0x54 bot/internal.(*Bot).runScan(0xc0000f84b0, 0xa69260, 0x20, 0x20, 0x0, 0xc0001fdf88, 0x4, 0xc00020df88) /home/me/Fatebot/internal/scanner.go:271 +0x7d bot/internal.(*Bot).Scanner.func1(0xc0000f84b0, 0xc0000f8d20, 0xc00002e7e0, 0x1) /home/me/Fatebot/internal/scanner.go:330 +0x125 created by bot/internal.(*Bot).Scanner

Thank you very much for report bug. I have fixed it now.

**Comment by supmyhava** [comment]
> > > > > > > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > > > > > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > > > > > > 
> > > > > > > 
> > > > > > > great update also liked the new icons you put in the scan section (:
> > > > > > 
> > > > > > 
> > > > > > Thank you very much 😆
> > > > > 
> > > > > 
> > > > > hi mate after a long time i didnt was here try your bot again
> > > > > (02:52:46) <@me> ?scan -cn PAYLOAD.COM/PAY (02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING... (02:54:16) * @[ME][U][196] (~[MU19@14C849C7.8992B6D3.5C536F8B.IP](mailto:MU19@14C849C7.8992B6D3.5C536F8B.IP)) Quit (Connection closed)
> > > > 
> > > > 
> > > > Is it happened with every bot you scan or just this one? i need to scope the problem for fix that.
> > > 
> > > 
> > > Oh and this one that's you just report to me you scan with you self or not? i really really need to scope a problem for fix that.
> > 
> > 
> > maybe this will tell you something
> > panic: runtime error: index out of range [3] with length 2
> > goroutine 80 [running]: bot/internal.Recv(0xc00032e3d8, 0x16, 0x3, 0x0, 0xc0001fd6d8) /home/me/Fatebot/internal/irc.go:26 +0xd6 bot/internal.ComdSetup(0x3, 0x7d84ec, 0x1, 0xc000219400, 0x1e) /home/me/Fatebot/internal/header.go:208 +0x47 bot/internal.SetupCaller(0x7d8b5b, 0x3, 0xc0002344b0) /home/me/Fatebot/internal/header.go:212 +0x54 bot/internal.(*Bot).runScan(0xc0000f84b0, 0xa69260, 0x20, 0x20, 0x0, 0xc0001fdf88, 0x4, 0xc00020df88) /home/me/Fatebot/internal/scanner.go:271 +0x7d bot/internal.(*Bot).Scanner.func1(0xc0000f84b0, 0xc0000f8d20, 0xc00002e7e0, 0x1) /home/me/Fatebot/internal/scanner.go:330 +0x125 created by bot/internal.(*Bot).Scanner
> 
> Thank you very much for report bug. I have fixed it now.

you're welcome (:
i will test it later

**Comment by boz3r** [comment]
> > > > > > > > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > > > > > > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > great update also liked the new icons you put in the scan section (:
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you very much 😆
> > > > > > 
> > > > > > 
> > > > > > hi mate after a long time i didnt was here try your bot again
> > > > > > (02:52:46) <@me> ?scan -cn PAYLOAD.COM/PAY (02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING... (02:54:16) * @[ME][U][196] (~[MU19@14C849C7.8992B6D3.5C536F8B.IP](mailto:MU19@14C849C7.8992B6D3.5C536F8B.IP)) Quit (Connection closed)
> > > > > 
> > > > > 
> > > > > Is it happened with every bot you scan or just this one? i need to scope the problem for fix that.
> > > > 
> > > > 
> > > > Oh and this one that's you just report to me you scan with you self or not? i really really need to scope a problem for fix that.
> > > 
> > > 
> > > maybe this will tell you something
> > > panic: runtime error: index out of range [3] with length 2
> > > goroutine 80 [running]: bot/internal.Recv(0xc00032e3d8, 0x16, 0x3, 0x0, 0xc0001fd6d8) /home/me/Fatebot/internal/irc.go:26 +0xd6 bot/internal.ComdSetup(0x3, 0x7d84ec, 0x1, 0xc000219400, 0x1e) /home/me/Fatebot/internal/header.go:208 +0x47 bot/internal.SetupCaller(0x7d8b5b, 0x3, 0xc0002344b0) /home/me/Fatebot/internal/header.go:212 +0x54 bot/internal.(*Bot).runScan(0xc0000f84b0, 0xa69260, 0x20, 0x20, 0x0, 0xc0001fdf88, 0x4, 0xc00020df88) /home/me/Fatebot/internal/scanner.go:271 +0x7d bot/internal.(*Bot).Scanner.func1(0xc0000f84b0, 0xc0000f8d20, 0xc00002e7e0, 0x1) /home/me/Fatebot/internal/scanner.go:330 +0x125 created by bot/internal.(*Bot).Scanner
> > 
> > 
> > Thank you very much for report bug. I have fixed it now.
> 
> you're welcome (: i will test it later
oh ok thank you very much

**Comment by supmyhava** [comment]
> > > > > > > > > > Sorry for misunderstanding(My english is really terrible), i mean the **internet connection of a bot device** just notice you because it can be happen any time.
> > > > > > > > > > oh and if you find any bug you can come back here and report or create a new issue, but to day update will be a little bit lately because i have a final high school test.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > great update also liked the new icons you put in the scan section (:
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Thank you very much 😆
> > > > > > > 
> > > > > > > 
> > > > > > > hi mate after a long time i didnt was here try your bot again
> > > > > > > (02:52:46) <@me> ?scan -cn PAYLOAD.COM/PAY (02:52:46) <@[ME][U][196]> 👁 [1]CORES START SCANNING... (02:54:16) * @[ME][U][196] (~[MU19@14C849C7.8992B6D3.5C536F8B.IP](mailto:MU19@14C849C7.8992B6D3.5C536F8B.IP)) Quit (Connection closed)
> > > > > > 
> > > > > > 
> > > > > > Is it happened with every bot you scan or just this one? i need to scope the problem for fix that.
> > > > > 
> > > > > 
> > > > > Oh and this one that's you just report to me you scan with you self or not? i really really need to scope a problem for fix that.
> > > > 
> > > > 
> > > > maybe this will tell you something
> > > > panic: runtime error: index out of range [3] with length 2
> > > > goroutine 80 [running]: bot/internal.Recv(0xc00032e3d8, 0x16, 0x3, 0x0, 0xc0001fd6d8) /home/me/Fatebot/internal/irc.go:26 +0xd6 bot/internal.ComdSetup(0x3, 0x7d84ec, 0x1, 0xc000219400, 0x1e) /home/me/Fatebot/internal/header.go:208 +0x47 bot/internal.SetupCaller(0x7d8b5b, 0x3, 0xc0002344b0) /home/me/Fatebot/internal/header.go:212 +0x54 bot/internal.(*Bot).runScan(0xc0000f84b0, 0xa69260, 0x20, 0x20, 0x0, 0xc0001fdf88, 0x4, 0xc00020df88) /home/me/Fatebot/internal/scanner.go:271 +0x7d bot/internal.(*Bot).Scanner.func1(0xc0000f84b0, 0xc0000f8d20, 0xc00002e7e0, 0x1) /home/me/Fatebot/internal/scanner.go:330 +0x125 created by bot/internal.(*Bot).Scanner
> > > 
> > > 
> > > Thank you very much for report bug. I have fixed it now.
> > 
> > 
> > you're welcome (: i will test it later
> 
> oh ok thank you very much

you did a great job in your last update 
bot is running for 3 days in a row perfect (didnt have any auth match but he is working and fast)

**Comment by boz3r** [comment]
OMG!!! Thank you very very much!!! 

Wait... really? You didn't get any bot from a scanner for 3 days?

**Comment by supmyhava** [comment]
> OMG!!! Thank you very very much!!!
> 
> Wait... really? You didn't get any bot from a scanner for 3 days?

yep didnt get anything yet =\
what IPs you are scanning ? and you got something some times

and another thing you should add to your bot is. when the bot if finish to the auto scan (-cn, -br, etc.) it will say on chan that he is done with that list.
Let it be known that he has stopped scanning

**Comment by supmyhava** [comment]
and your welcome

**Comment by boz3r** [comment]
Nope. I only test with my private network with a full scan process on VM (include payload implanting) because...
1) I don't want to get caught. I want to have a bright future (but in test with a public network i have comment all of payload implanting function. So it's only brute force didn't do any of payload implanting on a public network).
2) Bulletproof server is too expensive if compare with minimum wage of my country.

**On my test with a public network i found a lot of IPs that open default SSH port on CN or KR network. You can try to scan these network but i also get no auth match at the same as you. But i think it would found some weak device faster on these network.** 

Thank a lot for your recommendation i will think about it.
