### ISSUE TITLE
Bot dies

### ISSUE THREAD

**Issue by jAgentKaba** [boz3r/Fatebot#3]
![dead](https://user-images.githubusercontent.com/112901207/188503728-4c3e847e-2bc3-4d9b-967b-56978aedb677.png)

Bot dies using invalid commands with ? as prefix. Also delayed kill when using working commands. Using unrealircd go version 1.1.19 also tried latest go version on ubuntu 20.04 compiled native.

**Comment by boz3r** [comment]
Ohhh wait... did you set your IRC channel topic to autoscan command yet?

**Comment by boz3r** [comment]
hmmmmm... this is really weird, because mine is perfectly fine.

May i see the channel topic that you set please?

**Comment by jAgentKaba** [comment]
> hmmmmm... this is really weird, because mine is perfectly fine.
> 
> May i see the channel topic that you set please?
![autoscan2](https://user-images.githubusercontent.com/112901207/188722961-89a5870c-43c8-40e1-b79a-fa86f49e6ab4.png)

**Comment by boz3r** [comment]
> > hmmmmm... this is really weird, because mine is perfectly fine.
> > May i see the channel topic that you set please?
> > ![autoscan2](https://user-images.githubusercontent.com/112901207/188722961-89a5870c-43c8-40e1-b79a-fa86f49e6ab4.png)

ohhh... the autoscan command that i said is a "?autoscan" command
Example: ?autoscan -r my-server my-mips-server [myname]

**Comment by boz3r** [comment]
> > hmmmmm... this is really weird, because mine is perfectly fine.
> > May i see the channel topic that you set please?
> > ![autoscan2](https://user-images.githubusercontent.com/112901207/188722961-89a5870c-43c8-40e1-b79a-fa86f49e6ab4.png)

ohhh!!! and i am so sorry about that, i already forgot to add this self-spreading feature in to README. I'll add it soon.

**Comment by boz3r** [comment]
> 

The command is in "irc/commands.txt".

**Comment by boz3r** [comment]
> > > hmmmmm... this is really weird, because mine is perfectly fine.
> > > May i see the channel topic that you set please?
> > > ![autoscan2](https://user-images.githubusercontent.com/112901207/188722961-89a5870c-43c8-40e1-b79a-fa86f49e6ab4.png)
> 
> ohhh... the autoscan command that i said is a "?autoscan" command Example: ?autoscan -r my-server my-mips-server [myname]

The command are in "irc/commands.txt".

**Comment by jAgentKaba** [comment]
> 

![image](https://user-images.githubusercontent.com/112901207/188736758-1f77e5d4-01c8-4f24-beb7-246f9ea49a9c.png)
Still same issue =/

**Comment by boz3r** [comment]
you forget the square bracket.

**Comment by jAgentKaba** [comment]
> you forget the square bracket on the username, it should be [user].

Close this issue I am officialy an idiot! Thank you!!! I can not wait to test this!

**Comment by boz3r** [comment]
No!! No!! it's ok... my botnet is confused to use and i forgot to add this important self-spreading either!!! It's not your fault at all!!!
My botnet is brutely suck, i think it is gonna waste your time LMAO.
